services:
  - docker

script:
  - docker run
    -v $(pwd):/repo
    -e PROJECT=hollowverse-perf-monitor
    -e BRANCH=$TRAVIS_BRANCH
    -e COMMIT_ID=$TRAVIS_COMMIT
    -e IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    -e AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY
    -e CLOUDFRONT_DISTRIBUTION_ID
    hollowverse/build-env:lambda

notifications:
  email: false

